### ISSUE TITLE
Offtopic: How to treat downloaded fragment with GetMediaForFragmentList API

### ISSUE THREAD

**Issue by aroca** [aws/amazon-kinesis-video-streams-parser-library#46] opened 2019-02-09 20:26 UTC
Hi guys, did not know where to ask this. I've been playing a bit with kinesis and rekognition, and i reached the point where i can get the Framgment data with an API call for a fragment and i would like to see the "content" of that data. First as it is was a picture of the fragment. Is that possible with the data from the GetMediaForFragmentList API? I only put one fragment number in the list. My sole purpose is to try to get the "image" like a still picture/photograph and compare it to what it has detected via the rekognition processor. Hope it is clear. Thanks!

**Comment by zhiyua-git** [comment] 2019-02-19 00:55
Hi @aroca ,

By getting a picture from the fragment, do you know what is inside your fragment, are you wrapping picture into the frame or you are using some h264 frames? 
If you are directly putting pictures in, you would need to get frame data from FrameVisitor.FrameProcessor. 
If you are putting h264 frames, you will need decoder to construct the picture from h264 frames inside your fragment.

Hope it helps,
-ZH

**Comment by brahama** [comment] 2019-02-19 03:06
Hey @zhiyua-git ,
Thanks for the reply! What I did, that kinda works, but still I don't fully understand whats happening is the following:

- I do a kinesis get-records form my AmazonRekognition stream to get the timestamps of the first and last fragment that was processed.
- with those two values i can call the kinesisVideo.listFragments API to get all the fragments of the video stream in that timeframe (i only do 1 or 2 minute captures with kinesis_video_gstreamer_sample_app).
- i order those fragments by time in an array
- I feed that array to kinesisVideo.getMediaForFragmentList and create the media.webm

From that i open the file with VLC and to my surprise I see a really short (2 seconds) video, from part of what i capture in the previous step. But what i expect to see would be most of the capture, as i put the start and end timestamps of it.
Seems like i am making some mistake with the timestamps or something.
Will continue playing and get back!

Any tips are appreciated, and later i will try to play with turning a specific fragment or frame into a picture.

Thanks!

**Comment by vijaygj** [comment] 2019-02-19 04:16
> I feed that array to kinesisVideo.getMediaForFragmentList and create the media.webm

That is not sufficient. By default, MKV files are concatenated as a response of the GetMediaForFragmentList, hence the playback is only for the first file. Whereas file size should be big. You can build a single file instead of concatenating multiple MKV files using the following example - 

https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/e35344fd9f22ac128b55604c400764f3a80e71fe/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExampleTest.java#L49

**Comment by brahama** [comment] 2019-02-19 16:33
Thanks! I will give it a try this week and come back.

**Comment by brahama** [comment] 2019-03-02 13:29
Soo.. just to continue. As for what i wanted to try i do not need the whole movie.. i am just grabbing the fragment i need, and using ffmpeg to grab a frame and convert it to a picture.
Now what i want to do with that picture is try to see if i can add a bounding box with the "coordinates" returned from rekognition and draw it in the picture. I am still looking how to draw it with node. Seen a couple of solutions, like opencv(kinda overkill for this i think) and then imagemagick and the likes.
Will come back just to continue the progress, but you can close the issue if you want guys! Thanks for all the help. I will try the parser later, once i feel a bit more comfortable.. hehe.
Cheers!

**Comment by brahama** [comment] 2019-03-04 15:50
Probably this should go in an AWS Rekognition repo, but perhaps you guys can give a hand.
I grabbed the output from the kinesis stream that rekognition processor generated with this data:

```
{
    "InputInformation": {
        "KinesisVideo": {
            "StreamArn": "arn:aws:kinesisvideo:us-east-1::stream/kvideo-customer-1/154958062",
            "FragmentNumber": "91343852333181526535546170192994854702581800357",
            "ServerTimestamp": 1.551533115453E9,
            "ProducerTimestamp": 1.551533114844E9,
            "FrameOffsetInSeconds": 0.0
        }
    },
    "StreamProcessorInformation": {
        "Status": "RUNNING"
    },
    "FaceSearchResponse": [
        {
            "DetectedFace": {
                "BoundingBox": {
                    "Height": 0.23237179,
                    "Width": 0.17427884,
                    "Left": 0.34134614,
                    "Top": 0.28525642
                },
                "Confidence": 99.79235,
                "Landmarks": [
                    {
                        "X": 0.401795,
                        "Y": 0.38289854,
                        "Type": "eyeLeft"
                    },
                    {
                        "X": 0.46843415,
                        "Y": 0.3662039,
                        "Type": "eyeRight"
                    },
                    {
                        "X": 0.44253778,
                        "Y": 0.42725986,
                        "Type": "nose"
                    },
                    {
                        "X": 0.4250745,
                        "Y": 0.47506106,
                        "Type": "mouthLeft"
                    },
                    {
                        "X": 0.4698667,
                        "Y": 0.46396655,
                        "Type": "mouthRight"
                    }
                ],
                "Pose": {
                    "Pitch": -2.733125,
                    "Roll": -11.261545,
                    "Yaw": 1.8290821
                },
                "Quality": {
                    "Brightness": 59.24973,
                    "Sharpness": 12.911776
                }
            },
            "MatchedFaces": [
                {
                    "Similarity": 90.44609,
                    "Face": {
                        "BoundingBox": {
                            "Height": 0.429167,
                            "Width": 0.286111,
                            "Left": 0.437963,
                            "Top": 0.227778
                        },
                        "FaceId": "02500ec-1cd6-4135-afe8-2558e33e7609",
                        "Confidence": 99.9946,
                        "ImageId": "20a8329-0d1c-54fa-bcc4-cd1c28472b70",
                        "ExternalImageId": "name1"
                    }
                }
            ]
        }
    ]
}
```

Really dont understand why there are two Bounding Box objects, with different "coordinates". What i tried to do is to grab those coordinates
```
"BoundingBox": {
                    "Height": 0.23237179,
                    "Width": 0.17427884,
                    "Left": 0.34134614,
                    "Top": 0.28525642
                },
```
then I extract a picture from the frame with ffmpeg where I want to generate a bounding box in the picture. The issue is that when I convert those to the pixels coordinates that i use with gm module they are not where the face is..

```javascript
var left = 0;
    var top = 0;
    var height = 640;
    var width = 480;

    const boxLeft = 0.3810096;
    const boxTop = 0.48076922;
    const boxHeight = 0.40064102;
    const boxWidth = 0.30048078;

    left = width * boxLeft;
    top = height * boxTop;

.drawRectangle(Math.round(top), Math.round(left), Math.round(width * boxWidth)+top, Math.round(height * boxHeight)+left)
```
So i am not sure which ones to use. I tried to swap them, then adding the left and top to the other ones, as they are suppose to be relative. :(

Thanks guys!

**Comment by zhiyua-git** [comment] 2019-03-04 18:46
Hi @aroca ,

You can refer to the [sample](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/e35344fd9f22ac128b55604c400764f3a80e71fe/src/main/java/com/amazonaws/kinesisvideo/parser/examples/BoundingBoxImagePanel.java#L80) on how this boundingbox from Rekgonition output works. 

Thanks,
-ZH

**Comment by brahama** [comment] 2019-03-04 21:31
I think i am doing exactly that in my code. There is something obviously that i am not doing. or my data is incorrect. Or the module for drawing expects the data different. but just opening the picture in an editor, the coordinates i see in the bounding box map, do not match the face position. Will try to continue debugging this.

**Closed** 2020-06-23 15:49 UTC
