### ISSUE TITLE
No sample example of streaming video

### ISSUE THREAD

**Issue by sumitbadaya** [aws/amazon-kinesis-video-streams-parser-library#6] opened 2018-01-05 04:23 UTC
Hi, I cloned the amazon-kinesis-video-streams-parser-library and imported the project to my Eclipse IDE as a Maven application.
I am trying to figure out how to parse the video stream and display it on a video player or web browser live using Java application.

Is there any way I can do this? The source codes doesn't contain any sample application. Not sure how to make this work. Also the demo source files has errors related to certain imports and fails to import/download needed dependencies. **How should I run the program to stream video using amazon-kinesis-video-streams-parser-library?**

**Eclipse Java EE IDE for Web Developers.
Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600
OS- Ubuntu 16.04 TLS**

Thanks

**Comment by zhiyua-git** [comment] 2018-01-08 21:05
Hi Sumit,

The build issue is probably the same lombok and Eclipse Oxygen compatibility issue. I think you got it resolved [here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/17). 

The sample in this parser library repo is [KinesisVideoSample](https://github.com/aws/amazon-kinesis-video-streams-parser-library#visitors). What you will need from this example for getting the video stream is 
  1. Call GetMedia to stream video fragments out of your stream.
  2. Use the StreamingMkvParser to parse the returned the stream and apply the 
OutputSegmentMerger, FragmentMetadataVisitor visitors along with a local one as part of the same CompositeMkvElementVisitor visitor. 

One specific setting you may want to change for your case is the [StartSelectorType](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L113), you may want to set this to StartSelectorType.NOW to play current streaming video.

Thanks
-ZH

**Comment by sumitbadaya** [comment] 2018-01-09 05:51
Have too many issues in amazon's sample projects for Java (mostly related to missing dependency) .
Somehow got it resolved and got it working
But when I set **StartSelectorType.NOW** in my code, I don't get any frame. While the video is being played on amazon video stream console at the same moment. 
However **StartSelectorType.EARLIEST** gets me the video downloaded on my local disk.

Also how should I live stream the video locally on my computer or browser using this streams parser library? Do I need any video player to play the video live?

Any idea what could be wrong?

**Comment by bdhandap** [comment] 2018-01-12 07:17
Hey Sumit,

I apologize for the inconvenience. Can you please shed some light on the issue by answering the following questions? 

1. Did you ingest data through PutMedia in parallel, when you tried to retrieve fragment using GetMedia NOW? If not, can you start ingesting data and then try calling GetMedia NOW? 
2. What is the data retention period of the stream? The reason why I ask this question is if data retention is non-zero, then GetMedia EARLIEST would retrieve data even if there is no active PutMedia connection.
3. Also can you please share the stream-name and request id which you are trying to test? I can check our back-end logs. 

Also to answer your question about the video playback, one way to play the video locally is to save the merged mkv file retrieved via parser library and play it on a video player like VLC. To play it live, I'll update this thread with a better example.

Thanks
Babu

**Comment by sumitbadaya** [comment] 2018-01-12 10:29
1 - Did you ingest data through PutMedia in parallel, when you tried to retrieve fragment using GetMedia NOW? If not, can you start ingesting data and then try calling GetMedia NOW?
 **- Yes I tried but the video parser fetches 1 frame and program stops**

2 - What is the data retention period of the stream? The reason why I ask this question is if data retention is non-zero, then GetMedia EARLIEST would retrieve data even if there is no active PutMedia connection.
  **- Default. I didnt modify anything related to it.**

**Comment by vijaygj** [comment] 2018-02-06 06:18
Following diff is still work in progress but provides an example of playback with GetMedia API,

https://github.com/aws/amazon-kinesis-video-streams-parser-library/compare/master...vijaygj:frame-decode-render

**Comment by bdhandap** [comment] 2018-02-10 02:08
Hey Sumit,
We have added a [rendering sample](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRendererExampleTest.java) which explains the steps to get fragments using GetMedia API, decodes frame using JCodec and renders the video using JFrame.

**Closed by bdhandap** 2018-02-10 02:08 UTC
Labels: waiting for reply

**Comment by RushabhK23** [comment] 2018-03-08 13:43
@zhiyua-git @bdhandap  Can i use this library to store video in S3 bucket ???

**Comment by zhiyua-git** [comment] 2018-03-08 18:31
@RushabhK23 You can get your original video data and store it into S3 bucket if you want, but that will add up to the latency. 

You don't need to store video in S3 bucket. The video is already stored in Kinesis Video Streams with data retention you specify in the stream. With this library you can retrieve your data based on timestamp in the video or the timestamp when the video is stored. 

You can refer to the [examples](https://github.com/aws/amazon-kinesis-video-streams-parser-library#example) to get more information.

**Comment by RushabhK23** [comment] 2018-03-09 06:44
@zhiyua-git  Can you tell me steps to store it in S3 bucket ?? Even if it adds latency, I just want to store it and see in my S3.

**Comment by zhiyua-git** [comment] 2018-03-09 18:05
Hi @RushabhK23,

To save video as file, you can refer to this [example](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L202).

For more information about examples, you can check [README](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java).

To upload the file to S3, you can refer to [S3 developer guide](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html).

**Comment by RushabhK23** [comment] 2018-03-09 18:55
Hi @zhiyua-git Can we store video from KVS to S3 directly ?? So that when live stream comes in KVS and then after few latency, it can go directly to S3 storage ?? 

I have referred your example and saw process of saving video, but it makes its own new KVS stream which streams from  video file stored in system. I want to stream from webcam and then store a video file to S3. I can't find any proper steps or tutorial for this.

**Comment by zhiyua-git** [comment] 2018-03-09 19:14
Hi @RushabhK23,

You can remove the PutMediaWorker part in the example and use your own KVS live stream to call GetMedia in https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java#L120-L126. So the file stored will be from your stream. Does this work for you?

Can you also provide some information about what your scenario is? We can provide better suggestion based on what you need.

**Comment by bdhandap** [comment] 2018-03-09 19:27
@RushabhK23 We have a [C++ sample](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp#gstreamer-webcam-demo-application)  which ingests video from webcam in KVS. Unfortunately we don't have a Java sample code which does that. You can use that C++ sample to get live video into KinesisVideo and use [consumer parser library example](https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoExample.java) to get video fragments from KVS. After that as @zhiyua-git mentioned, you need to use AWS SDK for S3 to upload your video fragments into your S3 bucket. 


Kinesis Video has its own durable storage and saves your video fragments when you set the data retention to non-zero value. In order to answer your questions better, can you please let us know your use case on why do you want to store the video files in S3?

**Comment by RushabhK23** [comment] 2018-03-09 19:38
@zhiyua-git Will try your idea and then will tell u about my_stream solution. Is there anything else I have to change in parameter if I am using https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/main/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRendererExample.java example ??? As this example worked fine in Frame viewer for me 

@zhiyua-git My scenario is that I am using webcam for input stream and have done building AWS Kinesis SDK CPP script, which helped me to bring my stream to KVS and its video output in console. But I want to store it in S3 Bucket. By this library, I can store my stream in my PC. I wish to store directly to S3 so that afterwards I can stream that stored video in S3 later to Cloudfront and my team can stream it in thier browsers. 

@bdhandap Yup followed exactly same things which you mentioned in above. The problem is neither KVS nor S3 have visible storage for us. From visible, I mean it is stored by them but not able to see directly for simply downloading. We use KVS parser library to get fragments that is different thing. I wish to store directly to S3 so that afterwards I can stream that stored video in S3 later to Cloudfront and my team can stream it in thier browsers. 

Thanks both for quick responses. Learning alot

**Comment by turb0kat** [comment] 2018-03-10 04:55
We are adding HLS APIs which will enable you to stream directly from KVS to an off the shelf browser/mobile video player.  Please let us know if there are other reasons you would like to export to S3.

**Comment by RushabhK23** [comment] 2018-03-10 10:17
That will be good solution @turb0kat

**Comment by hpatruni** [comment] 2018-06-18 16:51
@turb0kat Could you please provide an update about the HLS APIs. We have use case to stream live video stored in KVS from the browser and mobile and are struggling to find a good sample code to stream online video from Javascript, Appreciate your help.

**Comment by Rishabhadept** [comment] 2018-09-18 11:53
Hi,

 I am also looking for the same use case and waiting for HLS APIs to be available for Java application. Are these API available or there is any ETA? Thanks.

**Comment by zhiyua-git** [comment] 2018-09-18 19:20
@hpatruni The [HLS](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-hls.html) is already available. 

@Rishabhadept The [HLS](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/how-hls.html) APIs are available. Related Java APIs documents is [here](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesisvideo/AmazonKinesisVideoArchivedMedia.html#getHLSStreamingSessionURL-com.amazonaws.services.kinesisvideo.model.GetHLSStreamingSessionURLRequest-).

**Comment by imvivek71** [comment] 2019-05-23 08:28
@zhiyua-git  Hi,  for a use case  I want to store the video streaming data for 15 days while the maximum retention hour is 7 days as per the docs. 

I tried to create a stream with more than 15 days and created successfully without any error,  so my question is does this stream store the data till 15 days and can I  retrieve it anytime within this period of 15 days. 

Thanks in advance!!!

**Comment by zhiyua-git** [comment] 2019-05-23 16:33
Hi @imvivek71 ,

We support max retention windows as ten years. 

"The retention period, in hours. The value you specify replaces the current value. The maximum value for this parameter is 87600 (ten years)."
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_UpdateDataRetention.html#API_UpdateDataRetention_RequestSyntax

Can you point me the doc link where you found the retention hour is 7 days? That would need to be corrected.

Thanks,
-ZH

**Comment by AG-Labs** [comment] 2019-08-06 08:05
> Have too many issues in amazon's sample projects for Java (mostly related to missing dependency) .
> Somehow got it resolved and got it working
> But when I set **StartSelectorType.NOW** in my code, I don't get any frame. While the video is being played on amazon video stream console at the same moment.
> However **StartSelectorType.EARLIEST** gets me the video downloaded on my local disk.
> 
> Also how should I live stream the video locally on my computer or browser using this streams parser library? Do I need any video player to play the video live?
> 
> Any idea what could be wrong?

What did you do to fix this, I seem to be having the problem.

**Comment by sajadmaster** [comment] 2020-01-22 08:55
AWS team,
Please make a working example, preferably with a gui, of a java application which gets media, parse it and show it on a video player. 
We've been struggling for days and don't know how to use kinesis video streams parser library.
Thank you

**Comment by aaron-freshwater-aws** [comment] 2020-01-22 16:19
Sample app is here:
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRendererExampleTest.java

As described in the README here:
https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/README.md

**Comment by sajadmaster** [comment] 2020-01-23 00:54
> Sample app is here:
> https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/src/test/java/com/amazonaws/kinesisvideo/parser/examples/KinesisVideoRendererExampleTest.java
> 
> As described in the README here:
> https://github.com/aws/amazon-kinesis-video-streams-parser-library/blob/master/README.md

Thank you. Problem solved. Just for future reference, don't forget to remove @ignore in the test file, otherwise it wouldn't work.
