### ISSUE TITLE
DEBUG / KinesisVideo: Received end-of-stream for ACKs. DEBUG / KinesisVideo: Finished reading ACKs stream DEBUG / KinesisVideo: Received all data, close INFO / KinesisVideo: Complete callback triggered for sampleKVS4 with statuscode 200

### ISSUE THREAD

**Issue by hameedriswan7** [aws/amazon-kinesis-video-streams-parser-library#83] opened 2020-03-02 11:35 UTC
DEBUG / KinesisVideo: Received end-of-stream for ACKs.
DEBUG / KinesisVideo: Finished reading ACKs stream
DEBUG / KinesisVideo: Received all data, close
INFO / KinesisVideo: Complete callback triggered for sampleKVS4 with statuscode 200

This is came when putmedia  running.kindly give example

**Comment by MushMal** [comment] 2020-03-02 18:01
@hameedriswan7 can you give a little more details as to what you are seeing? Is this the output from the producer SDK?

**Comment by hameedriswan7** [comment] 2020-03-03 06:23
@MushMal  while sending stream to AWS using putmedia. above callback method shows and stream not running. can i know reason for why it calls callback method?

**Comment by MushMal** [comment] 2020-03-03 19:29
@hameedriswan7 could you please describe your scenario? Is this related to the parser library or the producer SDK? Could you include the entire log? What asset are you using? Some demo apps are designed to stream out few frames and exit.

**Comment by hameedriswan7** [comment] 2020-03-04 05:52
DEBUG / KinesisVideo: PutFrame index: 1026, pts: 1126753754, dts: 1126753754, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 820, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 820 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 820 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1027, pts: 1127755066, dts: 1127755066, duration: 200000, keyFrame: true, track: 1
DEBUG / KinesisVideo: Kinesis Video client and stream metrics
	>> Overall storage size: 1073741824
	>> Available storage size: 1073610500
	>> Allocated storage size: 131324
	>> Total view allocation size: 172872
	>> Total streams frame rate: 9
	>> Total streams transfer rate: 29766
	>> Current view duration: 0
	>> Overall view duration: 31240000
	>> Current view size: 0
	>> Overall view size: 129756
	>> Current frame rate: 9.961970510498777
	>> Current transfer rate: 29766
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 100539, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 100539 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 100539 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: PutFrame index: 1028, pts: 1128756379, dts: 1128756379, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 1084, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 1084 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 1084 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: Received ACK bits: 76
{"EventType":"RECEIVED","FragmentTimecode":108900,"FragmentNumber":"91343852333181491972260273353598806020266865294"}


DEBUG / KinesisVideo: Received ACK bits: 77
{"EventType":"BUFFERING","FragmentTimecode":112104,"FragmentNumber":"91343852333181491977212033510740328002211633275"}


DEBUG / KinesisVideo: PutFrame index: 1029, pts: 1129757687, dts: 1129757687, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 920, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 920 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 920 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1030, pts: 1130758995, dts: 1130758995, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 846, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 846 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 846 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1031, pts: 1131760303, dts: 1131760303, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 768, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 768 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 768 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1032, pts: 1132761612, dts: 1132761612, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 687, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 687 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 687 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1033, pts: 1133762921, dts: 1133762921, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 754, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 754 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 754 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: Received ACK bits: 77
{"EventType":"PERSISTED","FragmentTimecode":108900,"FragmentNumber":"91343852333181491972260273353598806020266865294"}


DEBUG / KinesisVideo: PutFrame index: 1034, pts: 1134764230, dts: 1134764230, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 772, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 772 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 772 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1035, pts: 1135765520, dts: 1135765520, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 764, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 764 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 764 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1036, pts: 1136766811, dts: 1136766811, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 745, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 745 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 745 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1037, pts: 1137768102, dts: 1137768102, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 844, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 844 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 844 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting
DEBUG / KinesisVideo: PutFrame index: 1038, pts: 1138769394, dts: 1138769394, duration: 200000, keyFrame: false, track: 1
DEBUG / KinesisVideo: Data availability notification. Upload handle: 0, Size: 865, Duration 200000 
DEBUG / KinesisVideo: getStreamData fill 865 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: Streamed 865 bytes for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0
DEBUG / KinesisVideo: no data for stream KVSJ2ejq3g9zdAMbQC with uploadHandle 0, waiting

DEBUG / KinesisVideo: Received end-of-stream for ACKs.
DEBUG / KinesisVideo: Finished reading ACKs stream
DEBUG / KinesisVideo: Received all data, close
INFO / KinesisVideo: Complete callback triggered for KVSJ2ejq3g9zdAMbQC with statuscode 200


@MushMal  here is the complete log...when i am running RTSP camera using Putmedia to AWs..its sending frames to AWS for a minutes and then it suddenly stopped and waiting for feed..later 30 seconds it Move to callback method but application not stopped.

**Comment by MushMal** [comment] 2020-03-04 19:27
@hameedriswan7 , it seems that you are using Java SDK assets in which case the best would be to open an issue in that repository https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java

From the logs, it seems that you are streaming out frames just fine - the last index is 1038. The streaming keeps up with no buffer. 

Later, the ACK stream gets terminated then everything shuts down properly.

Is your application closing the stream?

One thing to note. If the application doesn't produce frames into the stream, the backend will timeout in 30 seconds and close the connection. Is this what you are seeing?

**Comment by zhiyua-git** [comment] 2020-03-12 16:51
Close as the issue is tracked in https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java/issues/89

**Closed by zhiyua-git** 2020-03-12 16:51 UTC
Labels: question
